AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CICD HW2 Lambda Templates
Resources:
  hw2lf1indexPhoto:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw2-lf1-index-photo
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf1-code
      Description: 'HW2 - index photos'
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::164930094788:role/service-role/hw2-lf1-index-photos-role-z6pvz8mv
      Environment:
        Variables:
          REGION: us-east-1

  hw2lf2searchPhoto:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw2-lf2-search-photo
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf2-code
      Description: 'HW2 - search photos'
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::164930094788:role/service-role/hw2-lf2-search-photos-role-pcqw40is
      Environment:
        Variables:
          REGION: us-east-1

  hw2lf3createFaceCollection:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw2-lf3-create-face-collection
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf3-code
      Description: 'HW2 - create Face Collection in Rekognition'
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::164930094788:role/service-role/hw2-create-collection-role-md80706t
      Environment:
        Variables:
          REGION: us-east-1
  