AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD HW2 Lambda Templates
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf1-code
      Description: 'HW2 - index photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::164930094788:role/service-role/hw2-lf1-index-photos-role-z6pvz8mv'
      Environment:
        Variables:
          REGION: us-east-1
